### ISSUE TITLE
ERROR: error loading package 'external': Package 'external' contains errors

### ISSUE THREAD

**Issue by dzintars** [oswee/oswee#285]
```bash
bazel run //scripts/minikube
INFO: Invocation ID: e2c03c71-95e3-47fc-afd9-817470033774
DEBUG: /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
ERROR: Traceback (most recent call last):
        File "/home/dzintars/code/github.com/dzintars/oswee/WORKSPACE", line 218, column 12, in <toplevel>
                k8s_go_deps()
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/io_bazel_rules_k8s/k8s/k8s_go_deps.bzl", line 36, column 31, in deps
                go_register_toolchains(go_version)
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/io_bazel_rules_go/go/private/sdk.bzl", line 409, column 13, in go_register_toolchains
                fail("go_register_toolchains: version set after go sdk rule declared ({})".format(", ".join([r["name"] for r in sdk_rules])))
Error in fail: go_register_toolchains: version set after go sdk rule declared (go_sdk)
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.061s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by dzintars** [comment]
It all started with this error:
```bash
» yarn bazel run //k8s/manifests/devcluster:persistent_volume.apply
yarn run v1.22.18
$ bazelisk run //k8s/manifests/devcluster:persistent_volume.apply
Starting local Bazel server and connecting to it...
INFO: Invocation ID: e71de231-17dd-417c-979c-c55cfcc8ed2a
DEBUG: /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Repository rules_python instantiated at:
  /home/dzintars/code/github.com/dzintars/oswee/WORKSPACE:15:19: in <toplevel>
  /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/prime/tools/build/workspace.bzl:58:17: in prime_dependencies
Repository rule http_archive defined at:
  /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_python/releases/download/0.9.0/rules_python-0.9.0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'rules_python':
   Traceback (most recent call last):
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.9.0/rules_python-0.9.0.tar.gz] to /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/rules_python/temp9061362313200100772/rules_python-0.9.0.tar.gz: GET returned 404 Not Found
ERROR: /home/dzintars/code/github.com/dzintars/oswee/WORKSPACE:15:19: fetching http_archive rule //external:rules_python: Traceback (most recent call last):
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.9.0/rules_python-0.9.0.tar.gz] to /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/rules_python/temp9061362313200100772/rules_python-0.9.0.tar.gz: GET returned 404 Not Found
ERROR: /home/dzintars/code/github.com/dzintars/oswee/k8s/manifests/devcluster/BUILD.bazel:8:11: //k8s/manifests/devcluster:persistent_volume.apply depends on @io_bazel_rules_k8s//k8s:apply.sh.tpl in repository @io_bazel_rules_k8s which failed to fetch. no such package '@rules_python//python': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.9.0/rules_python-0.9.0.tar.gz] to /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/rules_python/temp9061362313200100772/rules_python-0.9.0.tar.gz: GET returned 404 Not Found
ERROR: /home/dzintars/code/github.com/dzintars/oswee/k8s/manifests/devcluster/BUILD.bazel:8:11: //k8s/manifests/devcluster:persistent_volume.apply depends on @io_bazel_rules_k8s//k8s:stamper in repository @io_bazel_rules_k8s which failed to fetch. no such package '@rules_python//python': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/releases/download/0.9.0/rules_python-0.9.0.tar.gz] to /home/dzintars/.cache/bazel/_bazel_dzintars/45523854ce82ebfda51560aac6bfd7b7/external/rules_python/temp9061362313200100772/rules_python-0.9.0.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//k8s/manifests/devcluster:persistent_volume.apply' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.985s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (54 packages loaded, 258 targets configured)
FAILED: Build did NOT complete successfully (54 packages loaded, 258 targets configured)
    currently loading: @io_bazel_rules_k8s//k8s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I went down to the version update path.
Not sure what changed since last successful Bazel run.

**Comment by dzintars** [comment]
Updated versions
While there also renamed workspace to `oswee`
Expunged bazel cache.

**Comment by dzintars** [comment]
This is related to `rules_k8s`.

**Comment by dzintars** [comment]
`v0.6` works. Something wrong with latest `rules_k8s 0.7` version. And seems that `0.6` are compatible with `rules_docker v.0.25`. Downgraded back to `v0.6`.
