### ISSUE TITLE
Quay config image fails

### ISSUE THREAD

**Issue by dzintars** [oswee/oswee#374]
```bash
   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers

Startup timestamp:
Mon May  8 15:01:21 UTC 2023

Running all default config services
Traceback (most recent call last):
  File "/quay-registry/conf/init/supervisord_conf_create.py", line 128, in <module>
    generate_supervisord_config(
  File "/quay-registry/conf/init/supervisord_conf_create.py", line 93, in generate_supervisord_config
    rendered = template.render(config=config, logdriver=logdriver, hotreload=hotreload)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/app/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 343, in top-level template code
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'quotatotalworker'
```

**Comment by dzintars** [comment]
Don't use `image: quay.io/projectquay/quay:latest` tag. Instead use `image: quay.io/projectquay/quay:3.8.6`.
