### ISSUE TITLE
Gerrit: [plugin-manager-preloader] ERROR com.google.gerrit.pgm.Daemon : Thread plugin-manager-preloader threw exception

### ISSUE THREAD

**Issue by dzintars** [oswee/oswee#393]
Gerrit 3.8.1
Oauth plugin: master
SSO client configured

```bash
[2023-09-06T12:37:46.998Z] [main] INFO  com.google.gerrit.pgm.Daemon : Gerrit Code Review 3.8.1 ready
[2023-09-06T12:38:06.287Z] [plugin-manager-preloader] ERROR com.google.gerrit.pgm.Daemon : Thread plugin-manager-preloader threw exception
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: cannot convert null into a String
        at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.get(CaffeinatedGuavaLoadingCache.java:65)
        at com.googlesource.gerrit.plugins.manager.PluginsCentralCache.availablePlugins(PluginsCentralCache.java:41)
        at com.googlesource.gerrit.plugins.manager.OnStartStop$1.run(OnStartStop.java:53)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: cannot convert null into a String
        at com.googlesource.gerrit.plugins.manager.gson.SmartJson$1.apply(SmartJson.java:40)
        at com.googlesource.gerrit.plugins.manager.gson.SmartJson$1.apply(SmartJson.java:36)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.googlesource.gerrit.plugins.manager.gson.SmartJson.getOptionalString(SmartJson.java:35)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.lambda$getPluginArtifactInfo$2(JenkinsCiPluginsRepository.java:146)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.getPluginArtifactInfo(JenkinsCiPluginsRepository.java:146)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository$1.apply(JenkinsCiPluginsRepository.java:113)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository$1.apply(JenkinsCiPluginsRepository.java:109)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.getPluginInfo(JenkinsCiPluginsRepository.java:108)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.getList(JenkinsCiPluginsRepository.java:90)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.list(JenkinsCiPluginsRepository.java:73)
        at com.googlesource.gerrit.plugins.manager.repository.JenkinsCiPluginsRepository.list(JenkinsCiPluginsRepository.java:41)
        at com.googlesource.gerrit.plugins.manager.PluginsCentralLoader.load(PluginsCentralLoader.java:55)
        at com.googlesource.gerrit.plugins.manager.PluginsCentralLoader.load(PluginsCentralLoader.java:31)
        at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$SingleLoader.load(CaffeinatedGuavaLoadingCache.java:136)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2413)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2411)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2394)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.get(CaffeinatedGuavaLoadingCache.java:59)
        ... 3 more
```

**Comment by dzintars** [comment]
Tried 3.7.3 and 3.8.0 as well. Same.

**Comment by dzintars** [comment]
https://groups.google.com/g/repo-discuss/c/TxeJ9lvW6Is/m/NGLT2D5aAQAJ

**Comment by dzintars** [comment]
It also seems that Oauth plugin could be too new. Not sure what the deal there is.
